In [1]:
import numpy as np 

x= np.array([1,2,3,4,5])
type(x)

numpy.ndarray

In [12]:
y = np.array((3,4,5,6))

print(y[2] + y[3])


[3 4 5 6]
<class 'numpy.ndarray'>
11


In [5]:
z= np.array(42)
print(z)
type(z)

42


numpy.ndarray

In [6]:
z.ndim

0

In [7]:
x.ndim

1

1

In [24]:
a= np.array([2,3,4,5],dtype="S")

print(a.dtype)

newarr= a.astype("int")
print(newarr.dtype)

|S1
int64


In [25]:
a= np.array([2,3,4,5],dtype="S")

print(a.dtype)

newarr= a.astype("i")
print(newarr.dtype)

|S1
int32


In [27]:
y = np.array((3,4,5,6))

z= y.view()
x= y.copy()

print(z.base)
print(x.base)

[3 4 5 6]
None


In [30]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [31]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [34]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
arr2 = np.concatenate((arr1, arr2), axis=0)

print(arr,"\n",arr2)

[[1 2 5 6]
 [3 4 7 8]] 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [38]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

arr3 = np.hstack((arr1, arr2))
arr4 = np.vstack((arr1, arr2))
arr5 = np.dstack((arr1, arr2))

print(arr)
print()
print(arr3)
print()
print(arr4)
print()
print(arr5)


[[1 4]
 [2 5]
 [3 6]]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[[1 4]
  [2 5]
  [3 6]]]
